=== LogLine-Foundation/Ethics-is-Efficient/schemas/tdln/trust@1.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "DiamondCard v1 (trust)",
  "type": "object",
  "required": [
    "schema",
    "realm",
    "object",
    "did",
    "card_id",
    "decision",
    "refs",
    "runtime",
    "signatures"
  ],
  "properties": {
    "schema": {
      "const": "tdln/trust@1"
    },
    "realm": {
      "const": "trust"
    },
    "object": {
      "const": "diamondcard"
    },
    "did": {
      "type": "string"
    },
    "card_id": {
      "type": "string"
    },
    "decision": {
      "enum": [
        "ACK",
        "ASK",
        "NACK"
      ]
    },
    "refs": {
      "type": "object"
    },
    "runtime": {
      "type": "object"
    },
    "signatures": {
      "type": "object"
    }
  }
}

=== LogLine-Foundation/Ethics-is-Efficient/.out/card.json
{"card_id":"card:auto","decision":"ACK","did":"did:tdln:01KHEC71MZNKPX7N51R2T8VE2V","object":"diamondcard","realm":"trust","refs":{"inputs":[],"policy":{"cid":"b3:dc6370e8c94f9b4ffa4a86d934170837dc7baedc20c22ab9589950f973b9f2cf","rid":"auto"}},"runtime":{"engine":"wasmtime","exec":"wasm","fuel":0,"version":"resolver-v3"},"schema":"tdln/trust@1","signatures":{"alg":"ed25519-blake3","bundle_hash":"b3:60d719c9997d34091541be05e843f5e685211be6e21c7dfe816f840bfd1e56b1","sig_hex":"9badcf5adc7d9afb38734fc0f9c1386746988d7fb664df94fba281b0680bb3b7b79ef0bbc9b2ab4230da91e99f07aa06df3f10214aa802e2fdf48989b390d304"}}
